### ISSUE TITLE
stuck on "waiting for any device"

### ISSUE THREAD

**Issue by gijzelaerr** [fpv-wtf/butter#12]
hi! I have a DJI goggles V1 on `01.00.0606`, which is stuck in the DJI FPV system, it doesn't want to reboot to betaflight; there is no option "Switch to DJI Digital FPV System". I've reinstalled wtfOS, but still no luck. also a reset in the goggles shows no change. I thought I would try butter (on Windows) to reinstall the DJI firmware, but after the successful fastboot step after the goggles boot the flasher just says "waiting for any device". I can connect to the goggles using the DJI assistant without issues. Am I doing something wrong? I don't know of any other things to try. Thanks for any help in advance!

```
Please connect and power on your device
[ ] Waiting for DJI Recovery device to enumerate..
[-] This was a triumph. Proceed to flashing with fastboot.
< waiting for any device >
```

**Comment by j005u** [comment]
Sanity checks:

- You say you have V1 goggles - V1 goggles do not have alternate modes, they _only_ have the betaflight mode.
- Any chance you are using the V2 goggles package on V1 goggles or vica-versa? That would explain the issue.

**Comment by gijzelaerr** [comment]
thanks for the reply!

and great point! I always thought I had the v1 goggles somehow, but I guess I'm wrong. If you say that the v2 only has alternative modes, then I have the v2!

I managed to unstuck the menu by upgrading to the latest firmware, since the device is already rooted that worked for me. 

So I guess you are right, i was using the wrong version of the tool. Thanks!
