### ISSUE TITLE
i get this error when turning it on the the flash tool runnng #-9.

### ISSUE THREAD

**Issue by kshales** [fpv-wtf/butter#15]
I just get error #-9 , what ever the hell that means, 
the drone version is 1.04.000
is it too new ?

**Comment by j005u** [comment]
Butter only support DJI FPV Goggles V1 and V2 and the DIY air units. It does not support any DJI commercial drones.

What device are you trying to flash exactly?

**Comment by kshales** [comment]
The DJI fpv as I want to root it.

**Comment by j005u** [comment]
The DJI FPV cannot be rooted with fpv.wtf tools. See here: https://drone-hacks.com/ but ADB unlocking is paid.
