### ISSUE TITLE
Googles v1 Downgrade 608 to 606

### ISSUE THREAD

**Issue by Ciurrone** [fpv-wtf/butter#18]
Hi, I'm trying to downgrade the googles v1 from version 608 to version 606, I follow the procedure correctly, but once the firmware flash is finished, I still have version 608 on the googles.
Any suggestions ? Thanks in advance

could this be the problem?

![ddddd](https://github.com/fpv-wtf/butter/assets/65829753/d79e27d2-6007-4693-8ed0-2520e7e1331c)

**Comment by Ciurrone** [comment]
could this be the problem?
![ddddd](https://github.com/fpv-wtf/butter/assets/65829753/814fad4b-02c0-4a8f-963e-a451a19b3a24)

**Comment by 32dens** [comment]
Hi,
I have the same problem. Did you find a solution please?
Regards.

**Comment by Ciurrone** [comment]
> Hi, I have the same problem. Did you find a solution please? Regards.

I never tried again

**Comment by j005u** [comment]
Ignore the recovery partition error, it is not a problem.

It's normal for the reported FW version not to change when flashing with butter. Given the screenshot above I can safely say the downgrade actually succeeded and you can proceed to root on https://fpv.wtf.

Closing, but please re-open if you can't actually root.
