### ISSUE TITLE
how did you perform downgrade after flash

### ISSUE THREAD

**Issue by ketum** [fpv-wtf/butter#2]
Hello,

I have V2 goggles in 01.03.0000, I managed to flash them but I don't understand how to downgrade the firmware afterwards.
Is it possible to have some details on the follow-up to be given to the flash?
best regards Fred.

**Comment by j005u** [comment]
There's an issue where the firmware number cache is not cleaned after downgrading with butter, meaning you can't rely on the version number displayed in assistant or the goggles.

Just try to root, it should work now.

**Comment by ketum** [comment]
Thank you for your feedback, I will test it right away.
