### ISSUE TITLE
The problem of lowering the firmware version.

### ISSUE THREAD

**Issue by kotjara1** [fpv-wtf/butter#3]
I have a firmware with goggles 01.00.0607, I want to lower it to 0606. After oil processing in goggles, I see version 0606, and DJI Assistance determines the version 0607 in my goggles, and it displays the message that there is a discrepancy between individual firmware blocks and proposes to update it. Naturally, further penetration into the root does not pass and stops in the fifth step.
What to do? How can I correctly return the firmware 0606?  My glasses DJI FPV V2.
In the first photo, the result of the butter work, the second version, which I see with goggles and in the third photo you can see how my glasses were determined in DJI Assistance
![1671106011906](https://user-images.githubusercontent.com/120627898/207856926-cfccd1ca-3a2f-404e-8cef-3e4a8d0d41ae.jpg)
![1671106011891](https://user-images.githubusercontent.com/120627898/207856965-c7a11fb7-bac0-4269-b4d1-37e11193d34d.jpg)
![1671106011876](https://user-images.githubusercontent.com/120627898/207856980-2048ca2d-41c8-41e9-b528-b60115705967.jpg)

**Comment by j005u** [comment]
The 5th step is not require on V2 Goggles.

This is an issue with butter where an old firmware verrsion is cached on the goggles that gets fetched by the configurator.

If you saw success messages when running butter about flashing system, system_2, vendor, vendor_2 etc then you are downgraded and rootable. Don't trust the assistant.

You probably just need to go to the front page of the configurator and hit connect there.

**Comment by kotjara1** [comment]
Everything is fine! I see great OSD with goggles! Thanks a lot!
