### ISSUE TITLE
raw partition images

### ISSUE THREAD

**Issue by xviews** [fpv-wtf/butter#5]
Is it possible to create raw partition images?
I want to make an image of my Vista with the firmware v01.00.0600 because the image quality and range is better than with v01.00.0606.

**Comment by xviews** [comment]
Okay, I decrypted a DDD bin file with dji_imah_fwsig.py and created the system and vendor partition with sdat2img.py. 
Do I still have to apply the vendor.patch.dat and system.patch.dat with imgpatchtools? Because the patch.dat files are 0KB in size.

**Comment by 3DRacer** [comment]
I'm also very interested in rolling back the firmware Air Unit Lite / Caddx Vista / Runcam Link - V01.00.0600 to a Vista.

**Comment by j005u** [comment]
How new/old are both of your Vistas? 0606 was an update for a new HW revision (start of 2022?) for Vistas and there's a good chance 0600 will brick said SKUs. Specifically they swapped the flash/ram combo chip to another source.

Also, while I've heard a couple of people speculate on this before, I have 0 reason to beleive there was any range or quality loss with 0606. We've looked at the FW, the actual RF parts weren't updated.

As for extracting and decrypting - no, you don't need the patch.dat files (unless they are over 0KB, but I've never seen this in DJI FWs). You're on the right track, you'll also need all the other partitions (just decrypted, no further processing required) that are listed in the appropriate packages partitions file.

With that said, if you're sure you want to attempt the rollback, and are willing to risk butter not being able to recover for you afterwards (unlikely, but possible) then I can generate and link the appropriate packages for you.

In general we hope to one day get around to butter being able to deal with DDD archives directly, so we haven't put much effort into publishing the various FW versions.

**Comment by xviews** [comment]
Hey, thanks for the info. Had already tried a few days ago and it also worked .600 firmware to flash a Vista from 2021.
I have also created a video on how to create such packages and I find it very exciting myself.

I think, since there will be hardly any updates for the DJI V1 and V2 system, butter is already sufficient.

My comparison of the quality refers to 
https://youtu.be/mqmcge-jbMQ

The only thing where I still needed info is where the firmware version is stored, I found a file under Data where the firmware version is stored. 
I just do not remember what the file is called 🙄

Thank you for the feedback

**Comment by 3DRacer** [comment]
Hello Joonas,
I would like to try to bring my Vista from 2021 and 2022 (date of purchase) back to V01.00.0600. It would be great if you could provide the appropriate package.
Many thank for the feedback...

**Comment by xviews** [comment]
V01.00.0600_FPV_Air_Unit_Lite_dji_system
https://drive.google.com/file/d/1qR3kXNrOmvHuecaI5Epe6_bxCpjMMs2R/view?usp=share_link

**Comment by 3DRacer** [comment]
Thank you for the package. My Vista seems to have accepted the downgrade. Version in the DJI Assistant is given as **01.00.0606-** now. But unfortunately the Goggle still shows the message to different FW versions. Goggle is on 01.00.0600 also. As explained in the buttery description, the FW change is not displayed. Unfortunately I couldn't remove the annoying message in the goggle with it. Maybe there is another way other than updating all Vista. Many thanks for the help.

**Comment by 3DRacer** [comment]
Hello,
It's been some time now. I'm still looking for a way to get rid of the "incorrect firmware version" message on my DJI V1 goggles.
What is the name of the file that stores the firmware version number in Vista? I would like to reset my Vistas to the neutral factory state, where there is no message on the goggles.
