### ISSUE TITLE
Premade flashing packages for Air Unit - V01.00.0606

### ISSUE THREAD

**Issue by Firanight** [fpv-wtf/butter#6]
Hi, thanks for you job! Is there a way to have premade flashing packages for Air Unit - V01.00.0606, I need it to recover my air unit after chrome crash during wtfos install.. Maybe I just don't don't understand how can I do it but I only see package for V01.00.0608.

Thanks for your help!

**Comment by xviews** [comment]
Hey I created a package, hope it helps you.
https://drive.google.com/file/d/1I_zdqVhi-qHQq60vEq7K0Bl11toPfhsl/view?usp=share_link
If you want to create your own package, here is a video
https://www.youtube.com/watch?v=UtxJIX_UPZk

**Comment by Firanight** [comment]
Thank you very much i'm going to try it tonight!

**Comment by Firanight** [comment]
Thank you I manage to recover my air unit thanks to your file!
